spring.application.name=ipr-trustchain-backend

# Database
spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5432/ipr_trustchain_backend}
spring.datasource.username=${DB_USERNAME:postgres}
spring.datasource.password=${DB_PASSWORD:root}
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true

# Server
server.port=${PORT:8080}

# Logging
logging.level.com.iprtrustchain=INFO
logging.level.org.springframework.security=INFO

# JWT
jwt.secret=${JWT_SECRET:ThisIsMySuperSecretKeyForIPRTrustChainApplication2026}
jwt.expiration=${JWT_EXPIRATION:86400000}

# Gmail
spring.mail.host=${MAIL_HOST:smtp.gmail.com}
spring.mail.port=${MAIL_PORT:587}
spring.mail.username=${MAIL_USERNAME:YOUR_LOCAL_GMAIL}
spring.mail.password=${MAIL_PASSWORD:YOUR_LOCAL_APP_PASSWORD}

spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.required=true
spring.mail.properties.mail.smtp.connectiontimeout=5000
spring.mail.properties.mail.smtp.timeout=5000
spring.mail.properties.mail.smtp.writetimeout=5000

# Blockchain
blockchain.api.url=${BLOCKCHAIN_API_URL:http://localhost:3001}