spring.application.name=ipr-trustchain-backend

# Database
spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5432/ipr_trustchain_backend}
spring.datasource.username=${DB_USERNAME:postgres}
spring.datasource.password=${DB_PASSWORD:root}
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true

# Server
server.port=${PORT:8080}

# Logging
logging.level.com.iprtrustchain=INFO
logging.level.org.springframework.security=INFO

# JWT
jwt.secret=${JWT_SECRET:ThisIsMySuperSecretKeyForIPRTrustChainApplication2026}
jwt.expiration=${JWT_EXPIRATION:86400000}



# Blockchain
blockchain.api.url=${BLOCKCHAIN_API_URL:http://localhost:3001}